{
 "title": "Jmeter report",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Report summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total success",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(jmeter_success_total)", "legendFormat": "Success" }
   ]
  },
  {
   "title": "Total fail",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jmeter_success_ratio_failure)",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "Errors by HTTP Code",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (code) (rate(jmeter_succes_ratio_failure[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vusers (jmeter threads)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sum(jmeter_threads)", "legendFormat": "vusers" }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Request per second total",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(jmeter_success_ratio_success[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(jmeter_success_ratio_failure[$__rate_interval]))",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "Avg response by percentile",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "avg(jmeter_rt_summary{code=\"200\"}) by (quantile)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request per second by label",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(jmeter_success_ratio_total[$__rate_interval])) by (label)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time by transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "avg(rate(jmeter_rt_summary_sum{code=~\"1.*|2.*|3.*|4.*|5.*\"}[$__rate_interval]) / (rate(jmeter_rt_summary_count{code=~\"1.*|2.*|3.*|4.*|5.*\"}[$__rate_interval])>0)) by (label)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jmeter JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM free memory",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(jvm_memory_bytes_max {job=\"jmeter\"}) - (jvm_memory_bytes_used{job=\"jmeter\"})",
       "legendFormat": "{{instance}} - {{area}}"
      }
     ]
    },
    {
     "title": "GC % time",
     "type": "graph",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(jvm_gc_collection_seconds_sum{job=~\"jmeter\"}[1m])",
       "legendFormat": "{{instance}} - {{gc}} "
      }
     ]
    },
    {
     "title": "JVM heap  - free memory by pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_committed {job=~\"jmeter\"}) - (jvm_memory_pool_bytes_used{job=~\"jmeter\"}) ",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    },
    {
     "title": "JVM heap -  used memory by pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "(jvm_memory_pool_bytes_used{job=\"jmeter\"}) ",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    }
   ]
  }
 ]
}